import { Product, Seller, UserLocation, CategoryItem, Conversation, ChatMessage, Review } from "./types";

export const DEFAULT_LOCATIONS: UserLocation[] = [
  { id: "loc-1", name: "Jakarta Selatan", district: "Kebayoran Baru", city: "Jakarta Selatan", lat: -6.2415, lng: 106.8005 },
  { id: "loc-2", name: "Jakarta Barat", district: "Kebon Jeruk", city: "Jakarta Barat", lat: -6.1925, lng: 106.7725 },
  { id: "loc-3", name: "Jakarta Timur", district: "Jatinegara", city: "Jakarta Timur", lat: -6.2255, lng: 106.8715 },
  { id: "loc-4", name: "Jakarta Pusat", district: "Menteng", city: "Jakarta Pusat", lat: -6.1945, lng: 106.8345 },
  { id: "loc-5", name: "Depok", district: "Margonda", city: "Depok", lat: -6.3725, lng: 106.8315 },
  { id: "loc-6", name: "Tangerang Selatan", district: "Bintaro", city: "Tangerang Selatan", lat: -6.2845, lng: 106.7115 },
  { id: "loc-7", name: "Bekasi", district: "Bekasi Barat", city: "Bekasi", lat: -6.2385, lng: 106.9755 },
];

export const CURRENT_USER: Seller = {
  id: "user-me",
  name: "Gathan Pratama",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  rating: 4.9,
  reviewsCount: 16,
  listingsCount: 4,
  soldCount: 12,
  responseRate: "100%",
  responseTime: "< 10 menit",
  memberSince: "Januari 2023",
  location: "Kebayoran Baru, Jakarta Selatan",
  verified: true,
  phone: "0812-8899-2233",
};

export const MOCK_SELLERS: Record<string, Seller> = {
  "seller-andi": {
    id: "seller-andi",
    name: "Andi Pratama",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 23,
    listingsCount: 5,
    soldCount: 18,
    responseRate: "98%",
    responseTime: "< 15 menit",
    memberSince: "Maret 2022",
    location: "Kebayoran Baru, Jakarta Selatan",
    verified: true,
  },
  "seller-rizky": {
    id: "seller-rizky",
    name: "Rizky Fauzan",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 31,
    listingsCount: 4,
    soldCount: 27,
    responseRate: "95%",
    responseTime: "< 20 menit",
    memberSince: "Agustus 2021",
    location: "Margonda, Depok",
    verified: true,
  },
  "seller-sarah": {
    id: "seller-sarah",
    name: "Sarah Clarissa",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    rating: 5.0,
    reviewsCount: 42,
    listingsCount: 7,
    soldCount: 38,
    responseRate: "100%",
    responseTime: "< 5 menit",
    memberSince: "Juni 2021",
    location: "Bintaro Jaya, Tangerang Selatan",
    verified: true,
  },
  "seller-dimas": {
    id: "seller-dimas",
    name: "Dimas Anggoro",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    rating: 4.7,
    reviewsCount: 19,
    listingsCount: 3,
    soldCount: 14,
    responseRate: "92%",
    responseTime: "< 30 menit",
    memberSince: "Februari 2023",
    location: "Kebon Jeruk, Jakarta Barat",
    verified: true,
  },
  "seller-nadya": {
    id: "seller-nadya",
    name: "Nadya Aurelia",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 28,
    listingsCount: 6,
    soldCount: 22,
    responseRate: "99%",
    responseTime: "< 10 menit",
    memberSince: "November 2022",
    location: "Tebet, Jakarta Selatan",
    verified: true,
  },
};

export const CATEGORIES: CategoryItem[] = [
  { name: "Electronics", slug: "electronics", iconName: "Smartphone", color: "bg-blue-50 text-blue-600 border-blue-100", itemCount: 142 },
  { name: "Fashion", slug: "fashion", iconName: "Shirt", color: "bg-pink-50 text-pink-600 border-pink-100", itemCount: 98 },
  { name: "Furniture", slug: "furniture", iconName: "Armchair", color: "bg-amber-50 text-amber-600 border-amber-100", itemCount: 64 },
  { name: "Home & Living", slug: "home-living", iconName: "Home", color: "bg-emerald-50 text-emerald-600 border-emerald-100", itemCount: 85 },
  { name: "Sports", slug: "sports", iconName: "Dumbbell", color: "bg-orange-50 text-orange-600 border-orange-100", itemCount: 53 },
  { name: "Books", slug: "books", iconName: "BookOpen", color: "bg-purple-50 text-purple-600 border-purple-100", itemCount: 41 },
  { name: "Hobbies", slug: "hobbies", iconName: "Gamepad2", color: "bg-indigo-50 text-indigo-600 border-indigo-100", itemCount: 77 },
  { name: "Automotive", slug: "automotive", iconName: "Car", color: "bg-red-50 text-red-600 border-red-100", itemCount: 36 },
  { name: "Others", slug: "others", iconName: "Package", color: "bg-slate-50 text-slate-600 border-slate-100", itemCount: 29 },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "iPhone 13 128GB Midnight Battery Health 87%",
    price: 5200000,
    originalPrice: 8500000,
    category: "Electronics",
    condition: "Good",
    description: "Pemakaian pribadi tangan pertama. Kondisi fisik 95% mulus selalu pakai case and tempered glass. All sparepart original belum pernah service / bongkar. Kelengkapan fullset box dan kabel charger ori C-Lightning. Siap COD cek unit sepuasnya.",
    photos: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebayoran Baru",
    city: "Jakarta Selatan",
    distanceKm: 1.8,
    seller: MOCK_SELLERS["seller-andi"],
    postedAt: "30 menit lalu",
    isGoodDeal: true,
    isNearby: true,
    isNewListing: true,
    meetUpPreference: "Area Blok M Plaza / MRT Senayan / Gandaria City",
    status: "available",
  },
  {
    id: "prod-2",
    title: "Mechanical Keyboard Keychron K2 Wireless Hot-swappable",
    price: 750000,
    originalPrice: 1350000,
    category: "Electronics",
    condition: "Like New",
    description: "Keychron K2 v2 RGB Backlight Brown Switch. Baru dipakai 3 bulan jarang-jarang buat ngetik tugas doang. Kondisi normal 100%, keycaps bersih no shine, batre masih awet tahan seminggu. Box lengkap beserta kabel braided, keycap puller, switch puller.",
    photos: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Margonda",
    city: "Depok",
    distanceKm: 2.1,
    seller: MOCK_SELLERS["seller-rizky"],
    postedAt: "1 jam lalu",
    isGoodDeal: true,
    isNearby: true,
    meetUpPreference: "Stasiun UI / Margo City Depok",
    status: "available",
  },
  {
    id: "prod-3",
    title: "Meja Kerja Minimalis Bekant 120x80cm Rangka Kokoh",
    price: 450000,
    originalPrice: 1200000,
    category: "Furniture",
    condition: "Good",
    description: "Meja kerja / belajar kokoh tahan beban berat. Daun meja particle board tebal lapisan melamin anti gores. Kaki besi kokoh bisa disesuaikan ketinggiannya. Alasan jual mau pindah kosan. Wajib ambil sendiri atau COD sekitaran Jakbar.",
    photos: [
      "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebon Jeruk",
    city: "Jakarta Barat",
    distanceKm: 3.4,
    seller: MOCK_SELLERS["seller-dimas"],
    postedAt: "2 jam lalu",
    isGoodDeal: true,
    meetUpPreference: "Ambil langsung di tempat (Kebon Jeruk)",
    status: "available",
  },
  {
    id: "prod-4",
    title: "Nike Air Force 1 '07 Triple White Original Size 42",
    price: 850000,
    originalPrice: 1549000,
    category: "Fashion",
    condition: "Like New",
    description: "Beli di Foot Locker Kota Kasablanka. Cuma dipakai 2x acara nikahan indoor. Sol bawah masih tebal bintang utuh, insole bersih, no creasing parah. Box original dan struk pembelian masih tersimpan rapi.",
    photos: [
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Bintaro Jaya",
    city: "Tangerang Selatan",
    distanceKm: 2.8,
    seller: MOCK_SELLERS["seller-sarah"],
    postedAt: "3 jam lalu",
    isGoodDeal: false,
    isPriceDrop: true,
    meetUpPreference: "Bintaro Xchange / Stasiun Jurang Mangu",
    status: "available",
  },
  {
    id: "prod-5",
    title: "Headphone Sony WH-1000XM4 Noise Canceling Mulus",
    price: 2100000,
    originalPrice: 3899000,
    category: "Electronics",
    condition: "Good",
    description: "Headphone ANC terbaik di kelasnya. Baterai masih awet 28+ jam dengan ANC aktif. Earpad kulit sintetis masih bagus belum ngelupas. Lengkap hardcase carry pouch, kabel aux 3.5mm, adapter pesawat. Nego tipis bensin siap COD.",
    photos: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebayoran Baru",
    city: "Jakarta Selatan",
    distanceKm: 0.9,
    seller: MOCK_SELLERS["seller-andi"],
    postedAt: "4 jam lalu",
    isGoodDeal: true,
    isNearby: true,
    meetUpPreference: "MRT Haji Nawi / Cilandak Town Square",
    status: "available",
  },
  {
    id: "prod-6",
    title: "Nintendo Switch OLED White Joycon + Free 2 Game Fisik",
    price: 3800000,
    originalPrice: 4900000,
    category: "Hobbies",
    condition: "Like New",
    description: "Layar OLED jernih bening no burn-in, sudah terpasang tempered glass dari hari pertama. Joycon no drift garansi tes sepuasnya. Bonus game Zelda BOTW dan Mario Kart 8 Deluxe versi cartridge fisik! Dock dan charger original bawaan lengkap.",
    photos: [
      "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1612287233207-68c9bc88a5ea?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Bintaro Jaya",
    city: "Tangerang Selatan",
    distanceKm: 3.5,
    seller: MOCK_SELLERS["seller-sarah"],
    postedAt: "5 jam lalu",
    isGoodDeal: true,
    meetUpPreference: "Area Bintaro Sektor 7 / McD Bintaro",
    status: "available",
  },
  {
    id: "prod-7",
    title: "Sepeda Lipat Element Troy 16 Inch 10 Speed Chromoly",
    price: 2400000,
    originalPrice: 4200000,
    category: "Sports",
    condition: "Good",
    description: "Frame chromoly enteng dan rigid. Shifter Sensah 10 speed lancar jaya, rem hidrolik pakem. Sudah upgrade sadel empuk Selle Royal dan ban Kenda Koast masih tebal. Siap gowes CFD akhir pekan tanpa PR.",
    photos: [
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Tebet",
    city: "Jakarta Selatan",
    distanceKm: 3.1,
    seller: MOCK_SELLERS["seller-nadya"],
    postedAt: "6 jam lalu",
    isGoodDeal: true,
    meetUpPreference: "Stasiun Tebet / Taman Tebet Eco Park",
    status: "available",
  },
  {
    id: "prod-8",
    title: "Kamera Mirrorless Fujifilm X-T30 Silver Body Only Shutter Count 4rb",
    price: 7900000,
    originalPrice: 11500000,
    category: "Electronics",
    condition: "Good",
    description: "Sensor X-Trans IV warna fuji khas film simulation. Sensor bersih cling tanpa jamur, tombol scroll empuk responsif. SC rendah baru 4.120 jepretan. Baterai dapet 2 (1 ori + 1 third party), strap kulit fuji dan box buku panduan lengkap.",
    photos: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebayoran Baru",
    city: "Jakarta Selatan",
    distanceKm: 1.4,
    seller: MOCK_SELLERS["seller-andi"],
    postedAt: "7 jam lalu",
    isGoodDeal: false,
    isNearby: true,
    meetUpPreference: "Area Senayan City / Plaza Senayan",
    status: "available",
  },
  {
    id: "prod-9",
    title: "Kursi Kerja Ergonomis Pexio Regent Lumbar Support Adjustable",
    price: 1100000,
    originalPrice: 2199000,
    category: "Furniture",
    condition: "Like New",
    description: "Kursi ergonomis buat WFH seharian anti pegal pinggang. Sandaran mesh breathable adem, 3D armrest bisa naik turun geser, reclining lock 3 posisi. Hidrolik mulus bergaransi resmi Pexio sisa 1 tahun. Dijual karena ganti setup standing desk.",
    photos: [
      "https://images.unsplash.com/photo-1580481077195-c3a9a32296c0?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Tebet",
    city: "Jakarta Selatan",
    distanceKm: 2.5,
    seller: MOCK_SELLERS["seller-nadya"],
    postedAt: "8 jam lalu",
    isGoodDeal: true,
    isPriceDrop: true,
    meetUpPreference: "Ambil langsung di tempat atau janjian sekitar Tebet",
    status: "available",
  },
  {
    id: "prod-10",
    title: "Jaket Denim Levi's Trucker Jacket Original Size L",
    price: 350000,
    originalPrice: 1299000,
    category: "Fashion",
    condition: "Good",
    description: "Warna medium wash vintage natural. Bahan denim tebal 100% katun khas Levi's original Red Tab. Kancing logam kuningan komplit, no sobek / robek aneh. Ukuran tag L (lebar dada 56cm, panjang 66cm).",
    photos: [
      "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Margonda",
    city: "Depok",
    distanceKm: 1.2,
    seller: MOCK_SELLERS["seller-rizky"],
    postedAt: "10 jam lalu",
    isGoodDeal: true,
    isNearby: true,
    meetUpPreference: "KRL Stasiun Pondok Cina / Depok Baru",
    status: "available",
  },
  {
    id: "prod-11",
    title: "iPad 9th Gen 64GB WiFi Space Grey Fullset No Minus",
    price: 3400000,
    originalPrice: 4799000,
    category: "Electronics",
    condition: "Like New",
    description: "iPad 10.2 inci cocok buat kuliah, nulis catatan, dan nonton film. Layar True Tone mulus, sensor fingerprint Touch ID aktif lancar. Baterai awet sehat 93%. Bonus flip cover magnetik warna navy.",
    photos: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Bintaro Jaya",
    city: "Tangerang Selatan",
    distanceKm: 3.7,
    seller: MOCK_SELLERS["seller-sarah"],
    postedAt: "12 jam lalu",
    isGoodDeal: false,
    meetUpPreference: "Bintaro Plaza / Mall Pondok Indah",
    status: "available",
  },
  {
    id: "prod-12",
    title: "Rak Buku Minimalis Kayu Jati Belanda 4 Tingkat",
    price: 280000,
    originalPrice: 550000,
    category: "Furniture",
    condition: "Good",
    description: "Rak serbaguna motif serat pinus natural vernis gloss halus. Kokoh tidak goyang, muat puluhan buku dan hiasan pajangan. Dimensi: tinggi 120cm, lebar 60cm, kedalaman 28cm. Bisa dibongkar pasang mudah.",
    photos: [
      "https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1589834390005-5d4fb9bf3d32?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebon Jeruk",
    city: "Jakarta Barat",
    distanceKm: 4.0,
    seller: MOCK_SELLERS["seller-dimas"],
    postedAt: "14 jam lalu",
    isGoodDeal: true,
    meetUpPreference: "Area RCTI Kebon Jeruk / Mall Central Park",
    status: "available",
  },
  {
    id: "prod-13",
    title: "Gitar Akustik Yamaha F310 Original Natural Suara Renyah",
    price: 850000,
    originalPrice: 1450000,
    category: "Hobbies",
    condition: "Good",
    description: "Gitar legendaris pemula sampai intermediate. Action senar ceper nyaman tanpa buzzing. Senar baru diganti D'Addario 0.10. Body mulus terawat no retak. Dapet bonus tas softcase busa tebal dan capo fret.",
    photos: [
      "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Margonda",
    city: "Depok",
    distanceKm: 2.9,
    seller: MOCK_SELLERS["seller-rizky"],
    postedAt: "1 hari lalu",
    isGoodDeal: true,
    meetUpPreference: "Dmall Depok / KRL Pondok Cina",
    status: "available",
  },
  {
    id: "prod-14",
    title: "Mesin Kopi Espresso De'Longhi Dedica EC685 Red Edition",
    price: 1650000,
    originalPrice: 3200000,
    category: "Home & Living",
    condition: "Like New",
    description: "Mesin espresso compact 15 bar pump tekanan ideal untuk crema tebal. Steam wand lancar buat bikin latte art foaming susu. Pemakaian rumahan seminggu cuma 2-3 cangkir. Kelengkapan portafilter, basket single/double, tamper original bawaan.",
    photos: [
      "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Bintaro Jaya",
    city: "Tangerang Selatan",
    distanceKm: 3.5,
    seller: MOCK_SELLERS["seller-sarah"],
    postedAt: "1 hari lalu",
    isGoodDeal: true,
    isPriceDrop: true,
    meetUpPreference: "Pasar Modern Bintaro Sektor 7",
    status: "available",
  },
  {
    id: "prod-15",
    title: "Xiaomi Smart TV 43 Inch 4K HDR Android TV Siaran Digital",
    price: 2300000,
    originalPrice: 3800000,
    category: "Electronics",
    condition: "Good",
    description: "Resolusi tajam 4K UHD support Dolby Audio & DTS. Sudah Google TV Android bisa instal Netflix, YouTube, Vidio langsung tanpa set top box. Layar aman no dead pixel. Remote bluetooth dengan voice command lancar.",
    photos: [
      "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebon Jeruk",
    city: "Jakarta Barat",
    distanceKm: 5.5,
    seller: MOCK_SELLERS["seller-dimas"],
    postedAt: "1 hari lalu",
    isGoodDeal: false,
    meetUpPreference: "Ambil langsung di unit agar bisa tes layar",
    status: "available",
  },
  {
    id: "prod-16",
    title: "Helm NJS Kairoz Solid Glossy Black Size L Busa Empuk",
    price: 420000,
    originalPrice: 650000,
    category: "Automotive",
    condition: "Like New",
    description: "Helm half face kekinian visor clear tebal anti gores. Sudah terpasang spoiler bawaan elegan. Busa pipi empuk wangi terawat tidak pernah jatuh / kebentur. Sertifikasi SNI & DOT aman berkendara harian.",
    photos: [
      "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebayoran Baru",
    city: "Jakarta Selatan",
    distanceKm: 1.6,
    seller: MOCK_SELLERS["seller-andi"],
    postedAt: "1 hari lalu",
    isGoodDeal: true,
    isNearby: true,
    meetUpPreference: "MRT Fatmawati / Citos",
    status: "available",
  },
  {
    id: "prod-17",
    title: "Apple Watch SE 2nd Gen 44mm Midnight GPS Sport Band",
    price: 2700000,
    originalPrice: 4399000,
    category: "Electronics",
    condition: "Like New",
    description: "Beli akhir 2023 di iBox. Body mulus 98% terawat, battery health 96%. Lengkap kabel charger magnetic fast charge dan dus bawaan. Cocok buat tracking olahraga lari, renang, dan notifikasi iPhone.",
    photos: [
      "https://images.unsplash.com/photo-1509741102003-ca64bfe5f069?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Tebet",
    city: "Jakarta Selatan",
    distanceKm: 2.3,
    seller: MOCK_SELLERS["seller-nadya"],
    postedAt: "2 hari lalu",
    isGoodDeal: true,
    meetUpPreference: "Kota Kasablanka Mall / Tebet",
    status: "available",
  },
  {
    id: "prod-18",
    title: "Dumbbell Set Koper 20kg Cast Iron Chrome Lapisan Karet",
    price: 380000,
    originalPrice: 750000,
    category: "Sports",
    condition: "Good",
    description: "Set dumbbell komplit beserta koper plastik tebal. Plat beban kombinasi 1.25kg, 2.5kg, dan stik dengan grip anti slip. Ada batang penyambung panjang jadi barbel lurus. Siap gym di kamar hemat biaya.",
    photos: [
      "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Margonda",
    city: "Depok",
    distanceKm: 3.8,
    seller: MOCK_SELLERS["seller-rizky"],
    postedAt: "2 hari lalu",
    isGoodDeal: true,
    meetUpPreference: "Area Detos Depok / Kukusan",
    status: "available",
  },
  {
    id: "prod-19",
    title: "Drone DJI Mini 2 Fly More Combo 4K 3 Baterai + Tas",
    price: 4600000,
    originalPrice: 7200000,
    category: "Electronics",
    condition: "Good",
    description: "Drone enteng di bawah 249 gram anti ribet izin. Kamera tajam 4K 30fps stabil 3-axis gimbal. Jarak transmisi OcuSync 2.0 tembus jauh. Semua baterai charging cycle di bawah 25 kali, tidak kembung. Komplit tas original DJI.",
    photos: [
      "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Bintaro Jaya",
    city: "Tangerang Selatan",
    distanceKm: 6.8,
    seller: MOCK_SELLERS["seller-sarah"],
    postedAt: "2 hari lalu",
    isGoodDeal: true,
    meetUpPreference: "Living World Alam Sutera / Bintaro",
    status: "available",
  },
  {
    id: "prod-20",
    title: "Paket Buku Best Seller: Atomic Habits & Psychology of Money",
    price: 120000,
    originalPrice: 228000,
    category: "Books",
    condition: "Like New",
    description: "Buku terjemahan resmi Gramedia asli 100% no bajakan / fotokopi. Kondisi halaman bersih putih tanpa coretan stabilo atau tekukan. Dijual sepaket hemat untuk upgrade mindset awal tahun.",
    photos: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebayoran Baru",
    city: "Jakarta Selatan",
    distanceKm: 0.7,
    seller: MOCK_SELLERS["seller-andi"],
    postedAt: "3 hari lalu",
    isGoodDeal: true,
    isNearby: true,
    meetUpPreference: "Halte Busway CSW / Taman Martha Tiahahu Blok M",
    status: "available",
  },
  {
    id: "prod-21",
    title: "Sepatu Lari Asics GEL-Kayano 29 Size 42.5 Support Stability",
    price: 1200000,
    originalPrice: 2499000,
    category: "Sports",
    condition: "Good",
    description: "Sepatu lari kategori stability ternyaman untuk overpronation. Bantalan FlyteFoam Blast+ empuk dan membal. Baru diajak lari total 45km di aspal taman. Outsole karet AHAR masih sangat tebal belum botak.",
    photos: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Tebet",
    city: "Jakarta Selatan",
    distanceKm: 3.0,
    seller: MOCK_SELLERS["seller-nadya"],
    postedAt: "3 hari lalu",
    isGoodDeal: true,
    meetUpPreference: "Stasiun Manggarai / Tebet",
    status: "available",
  },
  {
    id: "prod-22",
    title: "Marshall Emberton Portable Bluetooth Speaker Black & Brass",
    price: 1450000,
    originalPrice: 2699000,
    category: "Electronics",
    condition: "Like New",
    description: "Suara khas Marshall warm dengan bass bulat True Stereophonic 360 derajat. Tahan air rating IPX7 aman dibawa nongkrong outdoor. Baterai tahan 20 jam. Fisik mulus seperti baru keluar toko, dus lengkap.",
    photos: [
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Margonda",
    city: "Depok",
    distanceKm: 2.2,
    seller: MOCK_SELLERS["seller-rizky"],
    postedAt: "3 hari lalu",
    isGoodDeal: true,
    meetUpPreference: "Pesona Square Mall Depok",
    status: "available",
  },
  {
    id: "prod-23",
    title: "Monitor Gaming LG UltraGear 24GN60R IPS 144Hz 1ms FreeSync",
    price: 1550000,
    originalPrice: 2350000,
    category: "Electronics",
    condition: "Good",
    description: "Panel IPS warna akurat sRGB 99% refresh rate 144Hz sangat smooth untuk main Valorant dan CS2. Bebas garis atau dead pixel. Port DisplayPort dan HDMI normal. Lengkap kaki stand original, adaptor listrik, kabel DP.",
    photos: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Kebon Jeruk",
    city: "Jakarta Barat",
    distanceKm: 4.7,
    seller: MOCK_SELLERS["seller-dimas"],
    postedAt: "4 hari lalu",
    isGoodDeal: false,
    meetUpPreference: "Janjian sekitar Mall Taman Anggrek / CP",
    status: "available",
  },
  {
    id: "prod-24",
    title: "Kacamata Ray-Ban Clubmaster Classic Green Polarized Original",
    price: 900000,
    originalPrice: 2350000,
    category: "Fashion",
    condition: "Like New",
    description: "Model ikonik frame hitam aksen gold lensa G-15 Polarized anti silau sinar matahari UV400. Engsel kokoh tulisan ukir kode frame jelas. Lengkap leather case hitam Ray-Ban original dan lap pembersih.",
    photos: [
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80"
    ],
    district: "Bintaro Jaya",
    city: "Tangerang Selatan",
    distanceKm: 2.7,
    seller: MOCK_SELLERS["seller-sarah"],
    postedAt: "4 hari lalu",
    isGoodDeal: true,
    isPriceDrop: true,
    meetUpPreference: "Bintaro Plaza / Lotte Mall Bintaro",
    status: "available",
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    sellerId: "seller-andi",
    reviewerName: "Budi Santoso",
    reviewerAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Penjual ramah banget, tepat waktu pas COD di MRT Blok M. Barangnya bener-bener seperti baru sesuai deskripsi!",
    date: "12 September 2026",
    itemTitle: "Sony WH-1000XM4"
  },
  {
    id: "rev-2",
    sellerId: "seller-andi",
    reviewerName: "Clarissa Dewi",
    reviewerAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Fast response banget gak nyampe 5 menit dibalas. Nego santai dan jujur soal kondisi barang. Recommended seller!",
    date: "5 September 2026",
    itemTitle: "Buku Atomic Habits"
  },
  {
    id: "rev-3",
    sellerId: "seller-sarah",
    reviewerName: "Fajar Nugraha",
    reviewerAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Barang mulus no minus. Enak diajak janjian di Bintaro Xchange. Makasih banyak kak!",
    date: "28 Agustus 2026",
    itemTitle: "iPad 9th Gen 64GB"
  }
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    productId: "prod-1",
    product: INITIAL_PRODUCTS[0],
    otherUser: MOCK_SELLERS["seller-andi"],
    lastMessage: "Boleh mas, besok sore sekitar jam 4 di Starbucks Blok M Plaza ya?",
    updatedAt: "10 menit lalu",
    unreadCount: 1,
  },
  {
    id: "conv-2",
    productId: "prod-2",
    product: INITIAL_PRODUCTS[1],
    otherUser: MOCK_SELLERS["seller-rizky"],
    lastMessage: "Penawaran Rp700.000 disetujui penjual. Mau COD kapan?",
    updatedAt: "1 jam lalu",
    unreadCount: 0,
  }
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  "conv-1": [
    {
      id: "msg-1-1",
      conversationId: "conv-1",
      senderId: "user-me",
      text: "Halo mas Andi, apakah unit iPhone 13 ini masih ada?",
      timestamp: "15:20",
      isRead: true,
    },
    {
      id: "msg-1-2",
      conversationId: "conv-1",
      senderId: "seller-andi",
      text: "Halo! Masih ada mas, barang siap cek fisik langsung.",
      timestamp: "15:22",
      isRead: true,
    },
    {
      id: "msg-1-3",
      conversationId: "conv-1",
      senderId: "user-me",
      text: "Bisa ketemuan besok untuk cek kondisi baterai dan kameranya?",
      timestamp: "15:25",
      isRead: true,
    },
    {
      id: "msg-1-4",
      conversationId: "conv-1",
      senderId: "seller-andi",
      text: "Boleh mas, besok sore sekitar jam 4 di Starbucks Blok M Plaza ya?",
      timestamp: "15:30",
      isRead: false,
    }
  ],
  "conv-2": [
    {
      id: "msg-2-1",
      conversationId: "conv-2",
      senderId: "user-me",
      text: "Halo mas Rizky, bisa nego Rp700.000 untuk Keychron K2?",
      timestamp: "Kemarin 14:10",
      isOffer: true,
      offerAmount: 700000,
      offerStatus: "accepted",
      isRead: true,
    },
    {
      id: "msg-2-2",
      conversationId: "conv-2",
      senderId: "seller-rizky",
      text: "Penawaran Rp700.000 disetujui penjual. Mau COD kapan?",
      timestamp: "Kemarin 14:15",
      isRead: true,
    }
  ]
};
